include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_return: error
    unused_import: error

linter:
  rules:
    - avoid_print
    - prefer_final_locals
    - prefer_const_constructors
    - always_declare_return_types
    - public_member_api_docs
